Repository CYS4srl/SensitiveDiscoverer, pull requests merged in 2024-03, with the labels that each got.

#45 Fix regex editing in options tab
  src/main/java/com/cys4/sensitivediscoverer/model/RegexEntity.java
Labels: fix/options

#44 Improve tables models
  src/main/java/com/cys4/sensitivediscoverer/model/LogsTableModel.java
  src/main/java/com/cys4/sensitivediscoverer/model/RegexListViewerTableModel.java
  src/main/java/com/cys4/sensitivediscoverer/tab/LoggerTab.java
Labels: refactor/logger, refactor/options

#46 High memory usage with many items to analyze
  src/main/java/com/cys4/sensitivediscoverer/RegexScanner.java
  src/main/java/com/cys4/sensitivediscoverer/component/LogsTable.java
  src/main/java/com/cys4/sensitivediscoverer/component/LogsTableContextMenu.java
  src/main/java/com/cys4/sensitivediscoverer/model/LogEntity.java
  src/main/java/com/cys4/sensitivediscoverer/model/LogsTableModel.java
  src/main/java/com/cys4/sensitivediscoverer/tab/LoggerTab.java
  src/test/java/com/cys4/sensitivediscoverer/RegexScannerTest.java
  src/test/java/com/cys4/sensitivediscoverer/mock/ByteArrayMock.java
  src/test/java/com/cys4/sensitivediscoverer/mock/HttpRequestMock.java
  src/test/java/com/cys4/sensitivediscoverer/mock/HttpResponseMock.java
Labels: fix/scanner, refactor/logger

#43 Improvement import/export Regex
  README.md
  src/main/java/com/cys4/sensitivediscoverer/RegexListViewer.java
  src/main/java/com/cys4/sensitivediscoverer/Utils.java
  src/main/java/com/cys4/sensitivediscoverer/model/RegexEntity.java
  src/main/java/com/cys4/sensitivediscoverer/tab/LoggerTab.java
  src/main/resources/TextUI_en_US.properties
  src/test/java/com/cys4/sensitivediscoverer/model/RegexEntityTest.java
Labels: feature/options, refactor/options

#48 General refactor
  src/main/java/burp/BurpExtender.java
  src/main/java/com/cys4/sensitivediscoverer/MainUI.java
  src/main/java/com/cys4/sensitivediscoverer/RegexScanner.java
  src/main/java/com/cys4/sensitivediscoverer/RegexSeeder.java
  src/main/java/com/cys4/sensitivediscoverer/Utils.java
  src/main/java/com/cys4/sensitivediscoverer/event/OptionsScannerUpdateListener.java
  src/main/java/com/cys4/sensitivediscoverer/event/OptionsScannerUpdateMaxSizeListener.java
  src/main/java/com/cys4/sensitivediscoverer/event/OptionsScannerUpdateNumThreadsListener.java
  src/main/java/com/cys4/sensitivediscoverer/model/HttpRecord.java
  src/main/java/com/cys4/sensitivediscoverer/model/RegexEntity.java
  src/main/java/com/cys4/sensitivediscoverer/model/UIOptions.java
  src/main/java/com/cys4/sensitivediscoverer/ui/LogsTable.java
  src/main/java/com/cys4/sensitivediscoverer/ui/LogsTableContextMenu.java
  src/main/java/com/cys4/sensitivediscoverer/ui/PopupMenuButton.java
  src/main/java/com/cys4/sensitivediscoverer/ui/RegexEditDialog.java
  src/main/java/com/cys4/sensitivediscoverer/ui/RegexListViewer.java
  src/main/java/com/cys4/sensitivediscoverer/ui/RegexListViewerTable.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/AboutTab.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/ApplicationTab.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/LoggerTab.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/OptionsTab.java
  src/main/java/com/cys4/sensitivediscoverer/utils/BurpUtils.java
  src/main/java/com/cys4/sensitivediscoverer/utils/FileUtils.java
  src/main/java/com/cys4/sensitivediscoverer/utils/ScannerUtils.java
  src/main/java/com/cys4/sensitivediscoverer/utils/SwingUtils.java
  src/main/java/com/cys4/sensitivediscoverer/utils/Utils.java
  src/main/resources/regexes/regex_general.jsonc
  src/main/resources/regexes/regex_token.jsonc
  src/main/resources/regexes/regex_url.jsonc
  src/test/java/com/cys4/sensitivediscoverer/model/RegexEntityTest.java
Labels: refactor/logger, refactor/options, refactor/scanner

#49 Add regex description in exported logger results
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/LoggerTab.java
Labels: feature/logger

#51 Fix exception while sorting Logger results
  src/main/java/com/cys4/sensitivediscoverer/model/LogsTableModel.java
  src/main/java/com/cys4/sensitivediscoverer/ui/LogsTable.java
Labels: fix/logger

#53 Regex list right-click context menu to edit/delete
  src/main/java/com/cys4/sensitivediscoverer/ui/LogsTable.java
  src/main/java/com/cys4/sensitivediscoverer/ui/RegexListViewer.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/LoggerTab.java
Labels: feature/options

#54 Update LICENSE information in source
  pom.xml
  src/main/java/burp/BurpExtender.java
  src/main/java/com/cys4/sensitivediscoverer/MainUI.java
  src/main/java/com/cys4/sensitivediscoverer/Messages.java
  src/main/java/com/cys4/sensitivediscoverer/RegexScanner.java
  src/main/java/com/cys4/sensitivediscoverer/RegexSeeder.java
  src/main/java/com/cys4/sensitivediscoverer/event/OptionsScannerUpdateListener.java
  src/main/java/com/cys4/sensitivediscoverer/event/OptionsScannerUpdateMaxSizeListener.java
  src/main/java/com/cys4/sensitivediscoverer/event/OptionsScannerUpdateNumThreadsListener.java
  src/main/java/com/cys4/sensitivediscoverer/model/HttpSection.java
  src/main/java/com/cys4/sensitivediscoverer/model/JsonRegexEntity.java
  src/main/java/com/cys4/sensitivediscoverer/model/LogEntity.java
  src/main/java/com/cys4/sensitivediscoverer/model/LogsTableModel.java
  src/main/java/com/cys4/sensitivediscoverer/model/RegexEntity.java
  src/main/java/com/cys4/sensitivediscoverer/model/RegexListContext.java
  src/main/java/com/cys4/sensitivediscoverer/model/RegexListViewerTableModel.java
  src/main/java/com/cys4/sensitivediscoverer/model/ScannerOptions.java
  src/main/java/com/cys4/sensitivediscoverer/ui/LogsTable.java
  src/main/java/com/cys4/sensitivediscoverer/ui/LogsTableContextMenu.java
  src/main/java/com/cys4/sensitivediscoverer/ui/PopupMenuButton.java
  src/main/java/com/cys4/sensitivediscoverer/ui/RegexEditDialog.java
  src/main/java/com/cys4/sensitivediscoverer/ui/RegexListViewer.java
  src/main/java/com/cys4/sensitivediscoverer/ui/RegexListViewerTable.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/AboutTab.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/ApplicationTab.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/LoggerTab.java
  src/main/java/com/cys4/sensitivediscoverer/ui/tab/OptionsTab.java
  src/main/java/com/cys4/sensitivediscoverer/utils/Utils.java
Labels: kind/documentation
